---
- name: Install
  hosts: localhost 
  become: True
  become_user: root
  gather_facts: false
  
  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
        name: yum-utils
        state: present  
    - name: Download Docker repository file using the get_url
      get_url:
        url: "https://download.docker.com/linux/centos/docker-ce.repo"
        dest: "/etc/yum.repos.d/docker-ce.repo"
        mode: 0644
    - name: Install Docker packages (engine) using yum module, reference https://docs.docker.com/engine/install/centos/#installation-methods
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present
    - name: Start Docker service using the systemd module
      systemd:
        name: docker
        state: started
        enabled: yes
    - name: Pull image and create the container using docker_container
      docker_image:
        name: buli750/final:latest
        source: pull      
    - name: Start the container using docker_container
      docker_container:
        name: tomcat_devops
        image: buli750/final:latest
        state: started
        tty: true
        auto_remove: true
        ports:
          - "8080:8080"
