---
- name: Install
  hosts: 192.168.8.107
  become: true
  become_user: root
  gather_facts: false

  tasks:
    - name: Install yum-utils (use the yum module)
      yum:
        name: yum-utils
        state: present

    - name: Download Docker repository file using the get_url
      get_url:
        url: "https://download.docker.com/linux/centos/docker-ce.repo"
        dest: "/etc/yum.repos.d/docker-ce.repo"
        mode: "0644"

    - name: Install Docker packages (engine) using yum module
      yum:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
          - docker-buildx-plugin
          - docker-compose-plugin
        state: present

    - name: Start Docker service using the systemd module
      systemd:
        name: docker
        state: started
        enabled: yes

    - name: Install Python
      yum:
        name: python
        state: present

    - name: Download get-pip.py
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip
      command: python /tmp/get-pip.py

    - name: Upgrade pip
      command: pip install --upgrade pip

    - name: Install docker-SDK
      pip:
        name: docker

    - name: Pull image and create the container using docker_container
      docker_image:
        name: buli750/final:latest
        source: pull

    - name: Start the container using docker_container
      docker_container:
        name: wizardly_cerf
        image: buli750/final:latest
        state: started
        tty: true
        auto_remove: true
        ports:
          - "8099:8099"

    - name: Exit Python interpreter
      command: echo "exit()" | ansible_python_interpreter
